ALTER TABLE "applications"
  ADD COLUMN "role_tags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "experience" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "availability" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "fit_reason" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "links" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "note" TEXT NOT NULL DEFAULT '';
